/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class unu_doi_trei_Main */

#ifndef _Included_unu_doi_trei_Main
#define _Included_unu_doi_trei_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     unu_doi_trei_Main
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_unu_doi_trei_Main_print
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
